# configs/env/default.yaml

xml_path: "assets/yuyuan.xml"

frame_skip: 50    
max_steps: 650     
render_mode: null   

randomization:
  pos_noise: [1.5, 1.5, 1.0]  # x, y, z 
  angle_noise: [0.3, 0.3, 0.2] # roll, pitch, yaw 

weights:
  mlp: "weights/best_hydro_model.pth"
  scaler_x: "weights/scaler_X.pkl"
  scaler_y: "weights/scaler_Y.pkl"
