name: "navigate"  

_target_: envs.tasks.navigation_task.NavigationTask

reward_weights:
  phi_dist: 350.0
  w_align_err: 2.5
  w_roll_err: 3.0
  w_sway_vel: 2.0
  time_penalty: 0.1
  w_accel: 0.05
  w_delta_accel: 0.5
  w_energy: 1.5
  bonus_roll: 0.2
  success: 1500.0
  w_final_bonus: 500.0

goals:
  success_dist: 1.0
  max_dist: 50.0
  target_speed: 1.5
  start_pos: [0.0, 0.0, 10.0]
  target_pos: [10.0, 0.0, 10.0]
